### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by hamlim** [hamlim/inline-mdx.macro#2]
The readme should show the required steps to getting started with using this macro.

Things I can think of off the top of my head:

1. How to install it (`npm i --save-dev inline-mdx.macro` or `yarn add inline-mdx.macro --dev`)
2. Installing `babel-plugin-macros` and adding that to your babel config
3. Links to the babel-plugin-macros user guide: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md

**Comment by kbondanza** [comment]
@hamlim ,

are you still accepting pull requests for this?

**Comment by hamlim** [comment]
Yea definitely!

**Comment by hamlim** [comment]
Resolved in #8
