### ISSUE TITLE
Remove imports requirement

### ISSUE THREAD

**Issue by kentcdodds** [hamlim/inline-mdx.macro#9]
I think you should be able to access the program node which you can use to access the body and insert the imports manually without requiring people to call the `imports()` function. Wanna give that a try?

I think this should do the trick:

```js
  // Process any imports and add them where `imports` was called from
  const { ast } = babel.transform(
    [`import {MDXTag} from '@mdx-js/tag'`].concat(mdxImports).join('\n'),
    { ast: true },
  )
  const imports = ast.program.body.map(impNode => {
    return t.importDeclaration(impNode.specifiers, impNode.source)
  })
  state.file.ast.program.body.unshift(...imports)
```

**Comment by kentcdodds** [comment]
It may be useful to double check that `MDXTag` is not already imported in the file as well I think.

**Comment by weyert** [comment]
Btw, you can also pass `skipExport: true`-option to the method `mdx.sync:()` to avoid export default to be included in the exported code.

**Comment by weyert** [comment]
Hmm, then it's not returning a valid functional component 😅

**Comment by hamlim** [comment]
Thanks for the suggestion! I myself won't have too much time to look into this, so if anyone else wants to take a look and open a PR, I would be happy to review!

**Comment by hamlim** [comment]
This should work out of the box with v1.0.0 now 👍🏼
